//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Propietaria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspection()
        {
            this.Inspection_employee = new HashSet<Inspection_employee>();
        }
    
        public int Inspection_id { get; set; }
        public int Car_id { get; set; }
        public int Client_id { get; set; }
        public bool is_dent { get; set; }
        public bool replacement_rubber { get; set; }
        public bool is_gat { get; set; }
        public bool is_broken_glass { get; set; }
        public bool state_rubber1 { get; set; }
        public bool state_rubber2 { get; set; }
        public bool state_rubber3 { get; set; }
        public bool state_rubber4 { get; set; }
        public string comment { get; set; }
        public System.DateTime date { get; set; }
        public bool state { get; set; }
        public int Employee_id { get; set; }
        public string Fuel_level { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inspection_employee> Inspection_employee { get; set; }
    }
}
