//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Propietaria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model_car
    {
        public int Model_id { get; set; }
        public int Brand_id { get; set; }
        public string Description { get; set; }
        public bool State { get; set; }
    
        public virtual Brand Brand { get; set; }
    }
}
