//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Propietaria.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int User_id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool state { get; set; }
        public int Employee_id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
